eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: kettleManage
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    database: 0
server:
  port: 8081
  servlet:
   context-path: /kmap/
zuul:
  routes:
    api-a:
      path: /manage/**
      service-id: kettleManage
