spring:
  application:
    name: eureka-server

server:
  port: 8080
  servlet:
    context-path: /eureka/
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/