server:
  port: 8088
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    api-a:
      serviceId: kettleManage
      path: /manage/**